[package]
name = "eth_tx_sign_offline"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy.workspace = true
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
qrcode.workspace = true
